import type { Labels } from '../types';

export const defaultLabels: Labels = {
  // Search form
  'search.title': 'Property Search',
  'search.location': 'Location',
  'search.propertyType': 'Property Type',
  'search.listingType': 'Listing Type',
  'search.priceRange': 'Price Range',
  'search.bedrooms': 'Bedrooms',
  'search.bathrooms': 'Bathrooms',
  'search.features': 'Features',
  'search.submit': 'Search',
  'search.reset': 'Reset',
  'search.forSale': 'For Sale',
  'search.forRent': 'For Rent',
  'search.holidayRent': 'Holiday Rent',
  'search.development': 'New Development',
  'search.anyLocation': 'All Locations',
  'search.anyType': 'All Types',
  'search.minPrice': 'Min Price',
  'search.maxPrice': 'Max Price',
  'search.any': 'Any',

  // Results
  'results.title': 'Search Results',
  'results.showing': 'Showing',
  'results.of': 'of',
  'results.properties': 'properties',
  'results.noResults': 'No properties found matching your criteria.',
  'results.sortBy': 'Sort by',
  'results.priceAsc': 'Price: Low to High',
  'results.priceDesc': 'Price: High to Low',
  'results.dateAsc': 'Oldest First',
  'results.dateDesc': 'Newest First',
  'results.featured': 'Featured First',

  // Property card
  'property.bedrooms': 'Beds',
  'property.bathrooms': 'Baths',
  'property.buildSize': 'Built',
  'property.plotSize': 'Plot',
  'property.viewDetails': 'View Details',
  'property.priceOnRequest': 'Price on Request',
  'property.featured': 'Featured',
  'property.addToFavorites': 'Add to Favorites',
  'property.removeFromFavorites': 'Remove from Favorites',

  // Property detail
  'detail.description': 'Description',
  'detail.features': 'Features',
  'detail.location': 'Location',
  'detail.contact': 'Contact Agent',
  'detail.similarProperties': 'Similar Properties',
  'detail.virtualTour': 'Virtual Tour',
  'detail.video': 'Video',

  // Inquiry form
  'inquiry.title': 'Make an Inquiry',
  'inquiry.name': 'Your Name',
  'inquiry.email': 'Email Address',
  'inquiry.phone': 'Phone Number',
  'inquiry.message': 'Message',
  'inquiry.submit': 'Send Inquiry',
  'inquiry.success': 'Thank you! Your inquiry has been sent.',
  'inquiry.error': 'Sorry, there was an error sending your inquiry. Please try again.',

  // Pagination
  'pagination.previous': 'Previous',
  'pagination.next': 'Next',
  'pagination.page': 'Page',

  // Favorites / Wishlist
  'favorites.title': 'My Wishlist',
  'favorites.properties': 'properties',
  'favorites.shareTitle': 'Email this wishlist',
  'favorites.friendEmail': "Friend's email (optional)",
  'favorites.messagePlaceholder': 'Check out these properties!',
  'favorites.send': 'Send Wishlist',
  'favorites.success': 'Wishlist sent successfully!',
  'favorites.error': 'Failed to send. Please try again.',
  'favorites.empty': 'No properties in your wishlist yet.',

  // General
  'general.loading': 'Loading...',
  'general.error': 'An error occurred. Please try again.',
  'general.close': 'Close',
};

export const spanishLabels: Partial<Labels> = {
  'search.title': 'Búsqueda de Propiedades',
  'search.location': 'Ubicación',
  'search.propertyType': 'Tipo de Propiedad',
  'search.listingType': 'Tipo de Listado',
  'search.priceRange': 'Rango de Precio',
  'search.bedrooms': 'Dormitorios',
  'search.bathrooms': 'Baños',
  'search.features': 'Características',
  'search.submit': 'Buscar',
  'search.reset': 'Reiniciar',
  'search.forSale': 'En Venta',
  'search.forRent': 'En Alquiler',
  'search.holidayRent': 'Alquiler Vacacional',
  'search.development': 'Obra Nueva',
  'search.anyLocation': 'Todas las Ubicaciones',
  'search.anyType': 'Todos los Tipos',
  'search.minPrice': 'Precio Mín.',
  'search.maxPrice': 'Precio Máx.',
  'search.any': 'Cualquiera',

  'results.title': 'Resultados de Búsqueda',
  'results.showing': 'Mostrando',
  'results.of': 'de',
  'results.properties': 'propiedades',
  'results.noResults': 'No se encontraron propiedades que coincidan con sus criterios.',
  'results.sortBy': 'Ordenar por',
  'results.priceAsc': 'Precio: Menor a Mayor',
  'results.priceDesc': 'Precio: Mayor a Menor',
  'results.dateAsc': 'Más Antiguos',
  'results.dateDesc': 'Más Recientes',
  'results.featured': 'Destacados Primero',

  'property.bedrooms': 'Dorm.',
  'property.bathrooms': 'Baños',
  'property.buildSize': 'Construido',
  'property.plotSize': 'Parcela',
  'property.viewDetails': 'Ver Detalles',
  'property.priceOnRequest': 'Precio a Consultar',
  'property.featured': 'Destacado',
  'property.addToFavorites': 'Añadir a Favoritos',
  'property.removeFromFavorites': 'Quitar de Favoritos',

  'detail.description': 'Descripción',
  'detail.features': 'Características',
  'detail.location': 'Ubicación',
  'detail.contact': 'Contactar Agente',
  'detail.similarProperties': 'Propiedades Similares',
  'detail.virtualTour': 'Tour Virtual',
  'detail.video': 'Vídeo',

  'inquiry.title': 'Realizar una Consulta',
  'inquiry.name': 'Su Nombre',
  'inquiry.email': 'Correo Electrónico',
  'inquiry.phone': 'Teléfono',
  'inquiry.message': 'Mensaje',
  'inquiry.submit': 'Enviar Consulta',
  'inquiry.success': '¡Gracias! Su consulta ha sido enviada.',
  'inquiry.error': 'Lo sentimos, hubo un error al enviar su consulta. Por favor, inténtelo de nuevo.',

  'favorites.title': 'Mi Lista de Deseos',
  'favorites.properties': 'propiedades',
  'favorites.shareTitle': 'Enviar esta lista por email',
  'favorites.friendEmail': 'Email de un amigo (opcional)',
  'favorites.messagePlaceholder': '¡Mira estas propiedades!',
  'favorites.send': 'Enviar Lista',
  'favorites.success': '¡Lista enviada con éxito!',
  'favorites.error': 'Error al enviar. Por favor, inténtelo de nuevo.',
  'favorites.empty': 'No hay propiedades en su lista de deseos.',

  'pagination.previous': 'Anterior',
  'pagination.next': 'Siguiente',
  'pagination.page': 'Página',

  'general.loading': 'Cargando...',
  'general.error': 'Se produjo un error. Por favor, inténtelo de nuevo.',
  'general.close': 'Cerrar',
};

export const germanLabels: Partial<Labels> = {
  'search.title': 'Immobiliensuche',
  'search.location': 'Standort',
  'search.propertyType': 'Immobilientyp',
  'search.listingType': 'Angebotsart',
  'search.priceRange': 'Preisspanne',
  'search.bedrooms': 'Schlafzimmer',
  'search.bathrooms': 'Badezimmer',
  'search.features': 'Ausstattung',
  'search.submit': 'Suchen',
  'search.reset': 'Zurücksetzen',
  'search.forSale': 'Zum Verkauf',
  'search.forRent': 'Zur Miete',
  'search.holidayRent': 'Ferienvermietung',
  'search.development': 'Neubau',
  'search.anyLocation': 'Alle Standorte',
  'search.anyType': 'Alle Typen',
  'search.minPrice': 'Min. Preis',
  'search.maxPrice': 'Max. Preis',
  'search.any': 'Beliebig',

  'results.title': 'Suchergebnisse',
  'results.showing': 'Zeige',
  'results.of': 'von',
  'results.properties': 'Immobilien',
  'results.noResults': 'Keine Immobilien gefunden, die Ihren Kriterien entsprechen.',

  'property.bedrooms': 'Schlafz.',
  'property.bathrooms': 'Bäder',
  'property.buildSize': 'Wohnfl.',
  'property.plotSize': 'Grundst.',
  'property.viewDetails': 'Details Anzeigen',
  'property.priceOnRequest': 'Preis auf Anfrage',

  'inquiry.title': 'Anfrage Stellen',
  'inquiry.name': 'Ihr Name',
  'inquiry.email': 'E-Mail-Adresse',
  'inquiry.phone': 'Telefonnummer',
  'inquiry.message': 'Nachricht',
  'inquiry.submit': 'Anfrage Senden',

  'favorites.title': 'Meine Merkliste',
  'favorites.properties': 'Immobilien',
  'favorites.shareTitle': 'Merkliste per E-Mail senden',
  'favorites.friendEmail': 'E-Mail eines Freundes (optional)',
  'favorites.messagePlaceholder': 'Schauen Sie sich diese Immobilien an!',
  'favorites.send': 'Merkliste Senden',
  'favorites.success': 'Merkliste erfolgreich gesendet!',
  'favorites.error': 'Senden fehlgeschlagen. Bitte versuchen Sie es erneut.',
  'favorites.empty': 'Keine Immobilien in Ihrer Merkliste.',

  'general.loading': 'Laden...',
  'general.close': 'Schließen',
};
