export interface DefaultLabel {
  key: string;
  category: string;
  translations: Record<string, string>;
}

export const LABEL_CATEGORIES = [
  { id: 'search', name: 'Search Form' },
  { id: 'results', name: 'Search Results' },
  { id: 'card', name: 'Property Card' },
  { id: 'detail', name: 'Property Detail' },
  { id: 'inquiry', name: 'Inquiry Form' },
  { id: 'wishlist', name: 'Wishlist' },
  { id: 'map', name: 'Map' },
  { id: 'chat', name: 'AI Chat' },
  { id: 'pagination', name: 'Pagination' },
  { id: 'mortgage', name: 'Mortgage Calculator' },
  { id: 'general', name: 'General' },
] as const;

export const DEFAULT_LABELS: DefaultLabel[] = [
  // ── Search Form ──────────────────────────────────────────
  { key: 'search_button', category: 'search', translations: { en: 'Search', es: 'Buscar' } },
  { key: 'reset_button', category: 'search', translations: { en: 'Reset', es: 'Restablecer' } },
  { key: 'advanced_search', category: 'search', translations: { en: 'Advanced Search', es: 'Busqueda Avanzada' } },
  { key: 'location_placeholder', category: 'search', translations: { en: 'Location', es: 'Ubicacion' } },
  { key: 'location_all', category: 'search', translations: { en: 'All Locations', es: 'Todas las Ubicaciones' } },
  { key: 'location_search', category: 'search', translations: { en: 'Search location...', es: 'Buscar ubicacion...' } },
  { key: 'location_dropdown1_label', category: 'search', translations: { en: 'Location', es: 'Ubicacion' } },
  { key: 'location_dropdown2_label', category: 'search', translations: { en: 'Sub-location', es: 'Sub-ubicacion' } },
  { key: 'location_dropdown3_label', category: 'search', translations: { en: 'Area', es: 'Area' } },
  { key: 'location_n_selected', category: 'search', translations: { en: '{n} selected', es: '{n} seleccionados' } },
  { key: 'location_select_parent', category: 'search', translations: { en: 'Select a location first', es: 'Seleccione una ubicacion primero' } },
  { key: 'listing_type_all', category: 'search', translations: { en: 'All', es: 'Todos' } },
  { key: 'listing_type_sale', category: 'search', translations: { en: 'For Sale', es: 'En Venta' } },
  { key: 'listing_type_rent', category: 'search', translations: { en: 'For Rent', es: 'En Alquiler' } },
  { key: 'listing_type_holiday', category: 'search', translations: { en: 'Holiday Rental', es: 'Alquiler Vacacional' } },
  { key: 'listing_type_development', category: 'search', translations: { en: 'New Development', es: 'Obra Nueva' } },
  { key: 'property_type', category: 'search', translations: { en: 'Property Type', es: 'Tipo de Propiedad' } },
  { key: 'property_type_all', category: 'search', translations: { en: 'All Types', es: 'Todos los Tipos' } },
  { key: 'property_type_placeholder', category: 'search', translations: { en: 'Search type...', es: 'Buscar tipo...' } },
  { key: 'property_type_search', category: 'search', translations: { en: 'Search type...', es: 'Buscar tipo...' } },
  { key: 'property_type_n_selected', category: 'search', translations: { en: '{n} selected', es: '{n} seleccionados' } },
  { key: 'bedrooms_label', category: 'search', translations: { en: 'Bedrooms', es: 'Dormitorios' } },
  { key: 'bedrooms_any', category: 'search', translations: { en: 'Any', es: 'Cualquiera' } },
  { key: 'bathrooms_label', category: 'search', translations: { en: 'Bathrooms', es: 'Banos' } },
  { key: 'bathrooms_any', category: 'search', translations: { en: 'Any', es: 'Cualquiera' } },
  { key: 'price_min', category: 'search', translations: { en: 'Min Price', es: 'Precio Minimo' } },
  { key: 'price_max', category: 'search', translations: { en: 'Max Price', es: 'Precio Maximo' } },
  { key: 'price_on_request', category: 'search', translations: { en: 'Price on Request', es: 'Precio bajo consulta' } },
  { key: 'built_area_label', category: 'search', translations: { en: 'Built Area (m2)', es: 'Superficie Construida (m2)' } },
  { key: 'plot_size_label', category: 'search', translations: { en: 'Plot Size (m2)', es: 'Tamano de Parcela (m2)' } },
  { key: 'features_label', category: 'search', translations: { en: 'Features', es: 'Caracteristicas' } },
  { key: 'reference_label', category: 'search', translations: { en: 'Reference', es: 'Referencia' } },
  { key: 'reference_placeholder', category: 'search', translations: { en: 'Enter reference...', es: 'Ingrese referencia...' } },
  { key: 'active_filters', category: 'search', translations: { en: 'Active Filters', es: 'Filtros Activos' } },
  { key: 'clear_all', category: 'search', translations: { en: 'Clear All', es: 'Limpiar Todo' } },
  { key: 'more_filters', category: 'search', translations: { en: 'More Filters', es: 'Mas Filtros' } },
  { key: 'features_search', category: 'search', translations: { en: 'Search features...', es: 'Buscar caracteristicas...' } },
  { key: 'features_no_results', category: 'search', translations: { en: 'No features found', es: 'No se encontraron caracteristicas' } },
  { key: 'quick_features', category: 'search', translations: { en: 'Quick Features', es: 'Caracteristicas Rapidas' } },

  // ── Search Results ───────────────────────────────────────
  { key: 'results_showing', category: 'results', translations: { en: 'Showing', es: 'Mostrando' } },
  { key: 'results_of', category: 'results', translations: { en: 'of', es: 'de' } },
  { key: 'results_properties', category: 'results', translations: { en: 'properties', es: 'propiedades' } },
  { key: 'results_count', category: 'results', translations: { en: '{count} properties found', es: '{count} propiedades encontradas' } },
  { key: 'results_no_results', category: 'results', translations: { en: 'No properties found', es: 'No se encontraron propiedades' } },
  { key: 'results_no_results_message', category: 'results', translations: { en: 'Try adjusting your search criteria', es: 'Intente ajustar sus criterios de busqueda' } },
  { key: 'sort_label', category: 'results', translations: { en: 'Sort by', es: 'Ordenar por' } },
  { key: 'sort_newest', category: 'results', translations: { en: 'Newest Listings', es: 'Mas Recientes' } },
  { key: 'sort_oldest', category: 'results', translations: { en: 'Oldest Listings', es: 'Mas Antiguos' } },
  { key: 'sort_recently_updated', category: 'results', translations: { en: 'Recently Updated', es: 'Actualizados Recientemente' } },
  { key: 'sort_oldest_updated', category: 'results', translations: { en: 'Oldest Updated', es: 'Actualizados Hace Tiempo' } },
  { key: 'sort_price_asc', category: 'results', translations: { en: 'Price: Low to High', es: 'Precio: Menor a Mayor' } },
  { key: 'sort_price_desc', category: 'results', translations: { en: 'Price: High to Low', es: 'Precio: Mayor a Menor' } },
  { key: 'sort_featured', category: 'results', translations: { en: 'Featured First', es: 'Destacados Primero' } },
  { key: 'sort_location', category: 'results', translations: { en: 'By Location', es: 'Por Ubicacion' } },
  { key: 'view_toggle', category: 'results', translations: { en: 'View toggle', es: 'Cambiar vista' } },
  { key: 'view_grid', category: 'results', translations: { en: 'Grid view', es: 'Vista cuadricula' } },
  { key: 'view_list', category: 'results', translations: { en: 'List view', es: 'Vista lista' } },
  { key: 'view_map', category: 'results', translations: { en: 'Map view', es: 'Vista mapa' } },
  { key: 'back_to_results', category: 'results', translations: { en: 'Back to Results', es: 'Volver a Resultados' } },

  // ── Property Card ────────────────────────────────────────
  { key: 'card_bedrooms', category: 'card', translations: { en: 'beds', es: 'hab.' } },
  { key: 'card_bathrooms', category: 'card', translations: { en: 'baths', es: 'banos' } },
  { key: 'card_build_size', category: 'card', translations: { en: 'Built', es: 'Construido' } },
  { key: 'card_plot_size', category: 'card', translations: { en: 'plot', es: 'parcela' } },
  { key: 'card_terrace_size', category: 'card', translations: { en: 'terrace', es: 'terraza' } },
  { key: 'card_own', category: 'card', translations: { en: 'Own', es: 'Propio' } },
  { key: 'card_view_details', category: 'card', translations: { en: 'View Details', es: 'Ver Detalles' } },
  { key: 'card_featured', category: 'card', translations: { en: 'Featured', es: 'Destacado' } },
  { key: 'card_for_sale', category: 'card', translations: { en: 'For Sale', es: 'En Venta' } },
  { key: 'card_for_rent', category: 'card', translations: { en: 'For Rent', es: 'En Alquiler' } },
  { key: 'card_holiday_rent', category: 'card', translations: { en: 'Holiday Rental', es: 'Alquiler Vacacional' } },
  { key: 'card_development', category: 'card', translations: { en: 'New Development', es: 'Obra Nueva' } },
  { key: 'card_price_on_request', category: 'card', translations: { en: 'Price on Request', es: 'Precio bajo consulta' } },
  { key: 'card_built_area', category: 'card', translations: { en: 'Built Area', es: 'Superficie' } },

  // ── Property Detail ──────────────────────────────────────
  { key: 'detail_description', category: 'detail', translations: { en: 'Description', es: 'Descripcion' } },
  { key: 'detail_features', category: 'detail', translations: { en: 'Features', es: 'Caracteristicas' } },
  { key: 'detail_specifications', category: 'detail', translations: { en: 'Specifications', es: 'Especificaciones' } },
  { key: 'detail_location', category: 'detail', translations: { en: 'Location', es: 'Ubicacion' } },
  { key: 'detail_similar', category: 'detail', translations: { en: 'Similar Properties', es: 'Propiedades Similares' } },
  { key: 'detail_back', category: 'detail', translations: { en: 'Back to Results', es: 'Volver a Resultados' } },
  { key: 'detail_share', category: 'detail', translations: { en: 'Share', es: 'Compartir' } },
  { key: 'detail_save', category: 'detail', translations: { en: 'Save', es: 'Guardar' } },
  { key: 'detail_saved', category: 'detail', translations: { en: 'Saved', es: 'Guardado' } },
  { key: 'detail_video', category: 'detail', translations: { en: 'Video', es: 'Video' } },
  { key: 'detail_virtual_tour', category: 'detail', translations: { en: 'Virtual Tour', es: 'Tour Virtual' } },
  { key: 'detail_pdf', category: 'detail', translations: { en: 'PDF', es: 'PDF' } },
  { key: 'detail_energy_rating', category: 'detail', translations: { en: 'Energy Rating', es: 'Certificado Energetico' } },
  { key: 'detail_community_fees', category: 'detail', translations: { en: 'Community Fees', es: 'Gastos de Comunidad' } },
  { key: 'detail_year_built', category: 'detail', translations: { en: 'Year Built', es: 'Ano de Construccion' } },
  { key: 'detail_price', category: 'detail', translations: { en: 'Price', es: 'Precio' } },
  { key: 'detail_bedrooms', category: 'detail', translations: { en: 'Bedrooms', es: 'Dormitorios' } },
  { key: 'detail_bathrooms', category: 'detail', translations: { en: 'Bathrooms', es: 'Banos' } },
  { key: 'detail_built_area', category: 'detail', translations: { en: 'Built Area', es: 'Superficie Construida' } },
  { key: 'detail_plot_size', category: 'detail', translations: { en: 'Plot Size', es: 'Parcela' } },
  { key: 'detail_terrace', category: 'detail', translations: { en: 'Terrace', es: 'Terraza' } },
  { key: 'detail_floor', category: 'detail', translations: { en: 'Floor', es: 'Planta' } },
  { key: 'detail_garden', category: 'detail', translations: { en: 'Garden', es: 'Jardin' } },
  { key: 'detail_orientation', category: 'detail', translations: { en: 'Orientation', es: 'Orientacion' } },
  { key: 'detail_parking', category: 'detail', translations: { en: 'Parking', es: 'Aparcamiento' } },
  { key: 'detail_per_month', category: 'detail', translations: { en: 'month', es: 'mes' } },
  { key: 'detail_status', category: 'detail', translations: { en: 'Status', es: 'Estado' } },
  { key: 'detail_type', category: 'detail', translations: { en: 'Type', es: 'Tipo' } },
  { key: 'detail_ref', category: 'detail', translations: { en: 'Ref', es: 'Ref' } },
  { key: 'detail_address', category: 'detail', translations: { en: 'Address', es: 'Direccion' } },

  // ── Inquiry Form ─────────────────────────────────────────
  { key: 'inquiry_title', category: 'inquiry', translations: { en: 'Contact Agent', es: 'Contactar Agente' } },
  { key: 'inquiry_first_name', category: 'inquiry', translations: { en: 'First Name', es: 'Nombre' } },
  { key: 'inquiry_last_name', category: 'inquiry', translations: { en: 'Last Name', es: 'Apellido' } },
  { key: 'inquiry_email', category: 'inquiry', translations: { en: 'Your Email', es: 'Tu Email' } },
  { key: 'inquiry_phone', category: 'inquiry', translations: { en: 'Your Phone', es: 'Tu Telefono' } },
  { key: 'inquiry_message', category: 'inquiry', translations: { en: 'Message', es: 'Mensaje' } },
  { key: 'inquiry_send', category: 'inquiry', translations: { en: 'Send Inquiry', es: 'Enviar Consulta' } },
  { key: 'inquiry_sending', category: 'inquiry', translations: { en: 'Sending...', es: 'Enviando...' } },
  { key: 'inquiry_success', category: 'inquiry', translations: { en: 'Your inquiry has been sent successfully.', es: 'Su consulta ha sido enviada correctamente.' } },
  { key: 'inquiry_error', category: 'inquiry', translations: { en: 'Failed to send inquiry. Please try again.', es: 'Error al enviar la consulta. Intentelo de nuevo.' } },
  { key: 'inquiry_privacy_prefix', category: 'inquiry', translations: { en: 'I accept the', es: 'Acepto la' } },
  { key: 'inquiry_privacy_label', category: 'inquiry', translations: { en: 'privacy policy', es: 'politica de privacidad' } },
  { key: 'inquiry_privacy_url', category: 'inquiry', translations: { en: '/privacy-policy', es: '/politica-de-privacidad' } },
  { key: 'inquiry_default_message', category: 'inquiry', translations: { en: 'I am interested in the property "{title}" (Ref: {ref}). Please contact me with more information.', es: 'Estoy interesado en la propiedad "{title}" (Ref: {ref}). Por favor, contacteme con mas informacion.' } },
  { key: 'inquiry_for_sale', category: 'inquiry', translations: { en: 'for sale', es: 'en venta' } },
  { key: 'inquiry_for_rent', category: 'inquiry', translations: { en: 'for rent', es: 'en alquiler' } },
  { key: 'inquiry_for_holiday_rent', category: 'inquiry', translations: { en: 'for holiday rent', es: 'en alquiler vacacional' } },

  // ── Wishlist ─────────────────────────────────────────────
  { key: 'wishlist_title', category: 'wishlist', translations: { en: 'Wishlist', es: 'Lista de Deseos' } },
  { key: 'wishlist_empty', category: 'wishlist', translations: { en: 'Your wishlist is empty', es: 'Tu lista de deseos esta vacia' } },
  { key: 'wishlist_remove', category: 'wishlist', translations: { en: 'Remove', es: 'Eliminar' } },
  { key: 'wishlist_share', category: 'wishlist', translations: { en: 'Share Wishlist', es: 'Compartir Lista' } },
  { key: 'wishlist_compare', category: 'wishlist', translations: { en: 'Compare', es: 'Comparar' } },
  { key: 'wishlist_shared_banner', category: 'wishlist', translations: { en: 'Shared wishlist', es: 'Lista compartida' } },
  { key: 'wishlist_clear_confirm', category: 'wishlist', translations: { en: 'Remove all properties from your wishlist?', es: 'Eliminar todas las propiedades de tu lista?' } },
  { key: 'wishlist_empty_hint', category: 'wishlist', translations: { en: 'Browse properties and tap the heart icon to save your favorites', es: 'Navega propiedades y pulsa el icono de corazon para guardar tus favoritos' } },
  { key: 'wishlist_sort', category: 'wishlist', translations: { en: 'Sort', es: 'Ordenar' } },
  { key: 'wishlist_share_text', category: 'wishlist', translations: { en: 'Check out my saved properties', es: 'Mira mis propiedades guardadas' } },
  { key: 'compare', category: 'wishlist', translations: { en: 'Compare', es: 'Comparar' } },
  { key: 'compare_properties', category: 'wishlist', translations: { en: 'Compare Properties', es: 'Comparar Propiedades' } },
  { key: 'compare_select_min', category: 'wishlist', translations: { en: 'Please select at least 2 properties to compare.', es: 'Seleccione al menos 2 propiedades para comparar.' } },
  { key: 'share_wishlist', category: 'wishlist', translations: { en: 'Share Your Wishlist', es: 'Compartir Tu Lista' } },
  { key: 'share_wishlist_desc', category: 'wishlist', translations: { en: 'Share this link with anyone to show them your saved properties:', es: 'Comparte este enlace para mostrar tus propiedades guardadas:' } },
  { key: 'email_wishlist', category: 'wishlist', translations: { en: 'Email Your Wishlist', es: 'Enviar Tu Lista por Email' } },
  { key: 'add_note', category: 'wishlist', translations: { en: 'Add Note', es: 'Anadir Nota' } },
  { key: 'add_personal_note', category: 'wishlist', translations: { en: 'Add a personal note...', es: 'Agregar una nota personal...' } },
  { key: 'note_placeholder', category: 'wishlist', translations: { en: 'Write your note here...', es: 'Escribe tu nota aqui...' } },
  { key: 'personal_message', category: 'wishlist', translations: { en: 'Personal Message', es: 'Mensaje Personal' } },
  { key: 'your_email_optional', category: 'wishlist', translations: { en: 'Your email (optional)', es: 'Tu email (opcional)' } },

  // ── Map ──────────────────────────────────────────────────
  { key: 'map_search_address', category: 'map', translations: { en: 'Search address...', es: 'Buscar direccion...' } },
  { key: 'map_radius', category: 'map', translations: { en: 'Radius', es: 'Radio' } },
  { key: 'map_view_all', category: 'map', translations: { en: 'View All', es: 'Ver Todo' } },
  { key: 'map_zones', category: 'map', translations: { en: 'Zones', es: 'Zonas' } },
  { key: 'map_properties', category: 'map', translations: { en: 'Properties', es: 'Propiedades' } },
  { key: 'map_list_view', category: 'map', translations: { en: 'List View', es: 'Vista de Lista' } },
  { key: 'map_map_view', category: 'map', translations: { en: 'Map View', es: 'Vista de Mapa' } },
  { key: 'map_unavailable', category: 'map', translations: { en: 'Map could not be loaded', es: 'No se pudo cargar el mapa' } },
  { key: 'zones', category: 'map', translations: { en: 'areas', es: 'zonas' } },

  // ── AI Chat ──────────────────────────────────────────────
  { key: 'chat_toggle', category: 'chat', translations: { en: 'Chat with AI', es: 'Chatear con IA' } },
  { key: 'chat_title', category: 'chat', translations: { en: 'Property Assistant', es: 'Asistente de Propiedades' } },
  { key: 'chat_welcome', category: 'chat', translations: { en: 'Ask me anything about our properties!', es: 'Preguntame lo que quieras sobre nuestras propiedades!' } },
  { key: 'chat_error', category: 'chat', translations: { en: 'Sorry, something went wrong. Please try again.', es: 'Lo sentimos, algo salio mal. Intentelo de nuevo.' } },
  { key: 'chat_placeholder', category: 'chat', translations: { en: 'Type your question...', es: 'Escribe tu pregunta...' } },

  // ── Pagination ───────────────────────────────────────────
  { key: 'pagination_prev', category: 'pagination', translations: { en: 'Previous', es: 'Anterior' } },
  { key: 'pagination_next', category: 'pagination', translations: { en: 'Next', es: 'Siguiente' } },
  { key: 'pagination_page', category: 'pagination', translations: { en: 'Page', es: 'Pagina' } },

  // ── Mortgage Calculator ──────────────────────────────────
  { key: 'mortgage_title', category: 'mortgage', translations: { en: 'Mortgage Calculator', es: 'Calculadora de Hipoteca' } },
  { key: 'mortgage_price', category: 'mortgage', translations: { en: 'Property Price', es: 'Precio de la Propiedad' } },
  { key: 'mortgage_down_payment', category: 'mortgage', translations: { en: 'Down Payment', es: 'Entrada' } },
  { key: 'mortgage_interest', category: 'mortgage', translations: { en: 'Interest Rate', es: 'Tasa de Interes' } },
  { key: 'mortgage_years', category: 'mortgage', translations: { en: 'Years', es: 'Anos' } },
  { key: 'mortgage_monthly', category: 'mortgage', translations: { en: 'Monthly Payment', es: 'Pago Mensual' } },

  // ── General ──────────────────────────────────────────────
  { key: 'loading', category: 'general', translations: { en: 'Loading...', es: 'Cargando...' } },
  { key: 'error', category: 'general', translations: { en: 'An error occurred', es: 'Ocurrio un error' } },
  { key: 'close', category: 'general', translations: { en: 'Close', es: 'Cerrar' } },
  { key: 'currency_label', category: 'general', translations: { en: 'Currency', es: 'Moneda' } },
  { key: 'language_label', category: 'general', translations: { en: 'Language', es: 'Idioma' } },
  { key: 'featured', category: 'general', translations: { en: 'Featured', es: 'Destacado' } },
  { key: 'cancel', category: 'general', translations: { en: 'Cancel', es: 'Cancelar' } },
  { key: 'clear', category: 'general', translations: { en: 'Clear', es: 'Limpiar' } },
  { key: 'copy', category: 'general', translations: { en: 'Copy', es: 'Copiar' } },
  { key: 'copied', category: 'general', translations: { en: 'Copied!', es: 'Copiado!' } },
  { key: 'save', category: 'general', translations: { en: 'Save', es: 'Guardar' } },
  { key: 'edit', category: 'general', translations: { en: 'Edit', es: 'Editar' } },
  { key: 'share', category: 'general', translations: { en: 'Share', es: 'Compartir' } },
  { key: 'send_email', category: 'general', translations: { en: 'Send Email', es: 'Enviar Email' } },
  { key: 'send_to', category: 'general', translations: { en: 'Send to:', es: 'Enviar a:' } },
  { key: 'sending', category: 'general', translations: { en: 'Sending...', es: 'Enviando...' } },
  { key: 'email', category: 'general', translations: { en: 'Email', es: 'Email' } },
  { key: 'email_error', category: 'general', translations: { en: 'Failed to send. Please try again.', es: 'Error al enviar. Intentelo de nuevo.' } },
  { key: 'email_sent', category: 'general', translations: { en: 'Email sent successfully!', es: 'Email enviado correctamente!' } },
  { key: 'download_pdf', category: 'general', translations: { en: 'Download PDF', es: 'Descargar PDF' } },
  { key: 'qr_code', category: 'general', translations: { en: 'QR Code', es: 'Codigo QR' } },
  { key: 'read_less', category: 'general', translations: { en: 'Read Less', es: 'Leer Menos' } },
  { key: 'read_more', category: 'general', translations: { en: 'Read More', es: 'Leer Mas' } },
  { key: 'view_all', category: 'general', translations: { en: 'View All Properties', es: 'Ver Todas las Propiedades' } },
  { key: 'view_details', category: 'general', translations: { en: 'View Details', es: 'Ver Detalles' } },
  { key: 'properties', category: 'general', translations: { en: 'properties', es: 'propiedades' } },
  { key: 'property_singular', category: 'general', translations: { en: 'property', es: 'propiedad' } },
  { key: 'type', category: 'general', translations: { en: 'Type', es: 'Tipo' } },
  { key: 'reference', category: 'general', translations: { en: 'Ref', es: 'Ref' } },
  { key: 'feature', category: 'general', translations: { en: 'Feature', es: 'Caracteristica' } },
  { key: 'no_results', category: 'general', translations: { en: 'No results', es: 'Sin resultados' } },
  { key: 'beds', category: 'general', translations: { en: 'beds', es: 'hab.' } },
  { key: 'baths', category: 'general', translations: { en: 'baths', es: 'banos' } },
  { key: 'bedrooms', category: 'general', translations: { en: 'Bedrooms', es: 'Dormitorios' } },
  { key: 'bathrooms', category: 'general', translations: { en: 'Bathrooms', es: 'Banos' } },
  { key: 'location', category: 'general', translations: { en: 'Location', es: 'Ubicacion' } },
  { key: 'price', category: 'general', translations: { en: 'Price', es: 'Precio' } },
  { key: 'wishlist', category: 'general', translations: { en: 'Wishlist', es: 'Lista de Deseos' } },
];

export const KEY_TO_CATEGORY: Record<string, string> = {};
for (const label of DEFAULT_LABELS) {
  KEY_TO_CATEGORY[label.key] = label.category;
}
