export interface DefaultLabel {
  key: string;
  category: string;
  translations: Record<string, string>;
}

export const LABEL_CATEGORIES = [
  { id: 'search', name: 'Search Form' },
  { id: 'results', name: 'Search Results' },
  { id: 'card', name: 'Property Card' },
  { id: 'detail', name: 'Property Detail' },
  { id: 'inquiry', name: 'Inquiry Form' },
  { id: 'wishlist', name: 'Wishlist' },
  { id: 'map', name: 'Map' },
  { id: 'chat', name: 'AI Chat' },
  { id: 'pagination', name: 'Pagination' },
  { id: 'mortgage', name: 'Mortgage Calculator' },
  { id: 'general', name: 'General' },
] as const;

export const DEFAULT_LABELS: DefaultLabel[] = [
  // ── Search Form ──────────────────────────────────────────
  { key: 'search_button', category: 'search', translations: { en: 'Search', es: 'Buscar' } },
  { key: 'reset_button', category: 'search', translations: { en: 'Reset', es: 'Restablecer' } },
  { key: 'advanced_search', category: 'search', translations: { en: 'Advanced Search', es: 'Búsqueda Avanzada' } },
  { key: 'location_placeholder', category: 'search', translations: { en: 'Location', es: 'Ubicación' } },
  { key: 'location_all', category: 'search', translations: { en: 'All Locations', es: 'Todas las Ubicaciones' } },
  { key: 'location_search', category: 'search', translations: { en: 'Search location...', es: 'Buscar ubicación...' } },
  { key: 'location_dropdown1_label', category: 'search', translations: { en: 'Location', es: 'Ubicación' } },
  { key: 'location_dropdown2_label', category: 'search', translations: { en: 'Sub Location', es: 'Sub-ubicación' } },
  { key: 'location_dropdown3_label', category: 'search', translations: { en: 'Area', es: 'Área' } },
  { key: 'location_n_selected', category: 'search', translations: { en: '{n} selected', es: '{n} seleccionados' } },
  { key: 'location_select_parent', category: 'search', translations: { en: 'Select a location first', es: 'Seleccione una ubicación primero' } },
  { key: 'listing_type_all', category: 'search', translations: { en: 'All', es: 'Todos' } },
  { key: 'listing_type_placeholder', category: 'search', translations: { en: 'Status', es: 'Estado' } },
  { key: 'listing_type_sale', category: 'search', translations: { en: 'For Sale', es: 'En Venta' } },
  { key: 'listing_type_rent', category: 'search', translations: { en: 'For Rent', es: 'En Alquiler' } },
  { key: 'listing_type_holiday', category: 'search', translations: { en: 'Holiday Rental', es: 'Alquiler Vacacional' } },
  { key: 'listing_type_development', category: 'search', translations: { en: 'New Development', es: 'Obra Nueva' } },
  { key: 'property_type', category: 'search', translations: { en: 'Property Type', es: 'Tipo de Propiedad' } },
  { key: 'property_type_all', category: 'search', translations: { en: 'Property Type', es: 'Tipo de Propiedad' } },
  { key: 'property_type_placeholder', category: 'search', translations: { en: 'Search type...', es: 'Buscar tipo...' } },
  { key: 'property_type_search', category: 'search', translations: { en: 'Search type...', es: 'Buscar tipo...' } },
  { key: 'property_type_n_selected', category: 'search', translations: { en: '{n} selected', es: '{n} seleccionados' } },
  { key: 'bedrooms_label', category: 'search', translations: { en: 'Bedrooms', es: 'Dormitorios' } },
  { key: 'bedrooms_any', category: 'search', translations: { en: 'Any', es: 'Cualquiera' } },
  { key: 'bedrooms_placeholder', category: 'search', translations: { en: 'Bedrooms', es: 'Dormitorios' } },
  { key: 'bathrooms_label', category: 'search', translations: { en: 'Bathrooms', es: 'Baños' } },
  { key: 'bathrooms_any', category: 'search', translations: { en: 'Any', es: 'Cualquiera' } },
  { key: 'bathrooms_placeholder', category: 'search', translations: { en: 'Bathrooms', es: 'Baños' } },
  { key: 'price_min', category: 'search', translations: { en: 'Min. Price', es: 'Precio Mínimo' } },
  { key: 'price_max', category: 'search', translations: { en: 'Max. Price', es: 'Precio Máximo' } },
  { key: 'price_on_request', category: 'search', translations: { en: 'Price on Request', es: 'Precio bajo consulta' } },
  { key: 'built_area_label', category: 'search', translations: { en: 'Built Area (m2)', es: 'Superficie Construida (m2)' } },
  { key: 'plot_size_label', category: 'search', translations: { en: 'Plot Size (m2)', es: 'Tamaño de Parcela (m2)' } },
  { key: 'features_label', category: 'search', translations: { en: 'Features', es: 'Características' } },
  { key: 'key_ready_label', category: 'search', translations: { en: 'Key ready', es: 'Llave en mano' } },
  { key: 'reference_label', category: 'search', translations: { en: 'Reference', es: 'Referencia' } },
  { key: 'reference_placeholder', category: 'search', translations: { en: 'Reference', es: 'Referencia' } },
  { key: 'active_filters', category: 'search', translations: { en: 'Active Filters', es: 'Filtros Activos' } },
  { key: 'clear_all', category: 'search', translations: { en: 'Clear All', es: 'Limpiar Todo' } },
  { key: 'more_filters', category: 'search', translations: { en: 'More Filters', es: 'Más Filtros' } },
  { key: 'features_search', category: 'search', translations: { en: 'Search features...', es: 'Buscar características...' } },
  { key: 'features_no_results', category: 'search', translations: { en: 'No features found', es: 'No se encontraron características' } },
  { key: 'quick_features', category: 'search', translations: { en: 'Quick Features', es: 'Características Rápidas' } },
  { key: 'terrace_label', category: 'search', translations: { en: 'Terrace (m²)', es: 'Terraza (m²)' } },
  { key: 'location_label', category: 'search', translations: { en: 'Location', es: 'Ubicación' } },
  { key: 'property_type_label', category: 'search', translations: { en: 'Type', es: 'Tipo' } },
  { key: 'price_label', category: 'search', translations: { en: 'Price', es: 'Precio' } },
  // Active-filter chips above the results ("Min Price: €200,000 ×")
  { key: 'filter_listing_type', category: 'search', translations: { en: 'Listing Type', es: 'Tipo de Operación' } },
  { key: 'filter_location', category: 'search', translations: { en: 'Location', es: 'Ubicación' } },
  { key: 'filter_locations', category: 'search', translations: { en: 'Locations', es: 'Ubicaciones' } },
  { key: 'filter_property_type', category: 'search', translations: { en: 'Property Type', es: 'Tipo de Propiedad' } },
  { key: 'filter_min_price', category: 'search', translations: { en: 'Min Price', es: 'Precio Mín.' } },
  { key: 'filter_max_price', category: 'search', translations: { en: 'Max Price', es: 'Precio Máx.' } },
  { key: 'filter_min_bedrooms', category: 'search', translations: { en: 'Min Beds', es: 'Dorm. Mín.' } },
  { key: 'filter_max_bedrooms', category: 'search', translations: { en: 'Max Beds', es: 'Dorm. Máx.' } },
  { key: 'filter_min_bathrooms', category: 'search', translations: { en: 'Min Baths', es: 'Baños Mín.' } },
  { key: 'filter_max_bathrooms', category: 'search', translations: { en: 'Max Baths', es: 'Baños Máx.' } },
  { key: 'filter_min_build_size', category: 'search', translations: { en: 'Min Build', es: 'Superficie Mín.' } },
  { key: 'filter_max_build_size', category: 'search', translations: { en: 'Max Build', es: 'Superficie Máx.' } },
  { key: 'filter_min_plot_size', category: 'search', translations: { en: 'Min Plot', es: 'Parcela Mín.' } },
  { key: 'filter_max_plot_size', category: 'search', translations: { en: 'Max Plot', es: 'Parcela Máx.' } },
  { key: 'filter_keyword', category: 'search', translations: { en: 'Keyword', es: 'Palabra clave' } },
  { key: 'filter_reference', category: 'search', translations: { en: 'Reference', es: 'Referencia' } },
  { key: 'filter_n_locations', category: 'search', translations: { en: '{n} locations', es: '{n} ubicaciones' } },
  { key: 'filter_n_selected', category: 'search', translations: { en: '{n} selected', es: '{n} seleccionados' } },
  { key: 'filter_remove', category: 'search', translations: { en: 'Remove {filter}', es: 'Quitar {filter}' } },
  // AI + voice search (search form buttons and panel)
  { key: 'ai_search_title', category: 'search', translations: { en: 'Search with AI', es: 'Buscar con IA' } },
  { key: 'ai_search_panel_title', category: 'search', translations: { en: 'AI Search', es: 'Búsqueda con IA' } },
  { key: 'ai_search_badge', category: 'search', translations: { en: 'AI', es: 'IA' } },
  { key: 'ai_search_back', category: 'search', translations: { en: 'Back to filters', es: 'Volver a los filtros' } },
  { key: 'ai_search_placeholder', category: 'search', translations: { en: 'Describe your dream property…', es: 'Describa la propiedad de sus sueños…' } },
  { key: 'ai_search_thinking', category: 'search', translations: { en: 'Reading…', es: 'Leyendo…' } },
  { key: 'ai_search_try', category: 'search', translations: { en: 'Try:', es: 'Pruebe:' } },
  { key: 'ai_search_example_1', category: 'search', translations: { en: 'modern apartment with sea views', es: 'apartamento moderno con vistas al mar' } },
  { key: 'ai_search_example_2', category: 'search', translations: { en: 'family villa with garden under 400k', es: 'villa familiar con jardín por menos de 400k' } },
  { key: 'ai_search_example_3', category: 'search', translations: { en: '2 bedroom rental near the beach', es: 'alquiler de 2 dormitorios cerca de la playa' } },
  { key: 'ai_search_nothing', category: 'search', translations: { en: 'That did not match anything we can search by. Try naming a place, a price or a number of bedrooms.', es: 'Eso no coincide con nada por lo que podamos buscar. Pruebe a indicar un lugar, un precio o un número de dormitorios.' } },
  { key: 'ai_search_error', category: 'search', translations: { en: 'That search could not be understood. Please try again.', es: 'No se ha podido entender esa búsqueda. Inténtelo de nuevo.' } },
  { key: 'ai_voice_title', category: 'search', translations: { en: 'Voice Search', es: 'Búsqueda por Voz' } },
  { key: 'ai_voice_start', category: 'search', translations: { en: 'Speak your search', es: 'Diga su búsqueda' } },
  { key: 'ai_voice_stop', category: 'search', translations: { en: 'Stop listening', es: 'Dejar de escuchar' } },
  { key: 'ai_voice_done', category: 'search', translations: { en: 'Done speaking', es: 'He terminado' } },
  { key: 'ai_voice_type_instead', category: 'search', translations: { en: 'Type instead', es: 'Escribir en su lugar' } },
  { key: 'ai_voice_tap', category: 'search', translations: { en: 'Tap the mic and say what you are looking for', es: 'Pulse el micrófono y diga lo que busca' } },
  { key: 'ai_voice_listening_now', category: 'search', translations: { en: 'Listening… speak now', es: 'Escuchando… hable ahora' } },
  { key: 'ai_voice_understanding', category: 'search', translations: { en: 'Understanding…', es: 'Interpretando…' } },
  { key: 'ai_voice_try_again', category: 'search', translations: { en: 'Tap the mic to try again', es: 'Pulse el micrófono para intentarlo de nuevo' } },
  { key: 'ai_voice_example', category: 'search', translations: { en: 'For example: “3 bedroom villa with a pool under 500,000”', es: 'Por ejemplo: “villa de 3 dormitorios con piscina por menos de 500.000”' } },
  { key: 'ai_voice_nothing', category: 'search', translations: { en: 'We couldn’t pick out a search from that. Try saying a place, a price or a number of bedrooms.', es: 'No hemos podido sacar una búsqueda de eso. Pruebe a decir un lugar, un precio o un número de dormitorios.' } },
  { key: 'ai_voice_denied', category: 'search', translations: { en: 'The microphone could not be used. Allow it in your browser, or type your search instead.', es: 'No se pudo usar el micrófono. Permítalo en su navegador o escriba su búsqueda.' } },
  { key: 'ai_voice_error', category: 'search', translations: { en: 'That could not be understood. Please try again or type your search.', es: 'No se ha podido entender. Inténtelo de nuevo o escriba su búsqueda.' } },

  // ── Search Results ───────────────────────────────────────
  { key: 'results_showing', category: 'results', translations: { en: 'Showing', es: 'Mostrando' } },
  { key: 'results_of', category: 'results', translations: { en: 'of', es: 'de' } },
  { key: 'results_properties', category: 'results', translations: { en: 'properties', es: 'propiedades' } },
  { key: 'results_count', category: 'results', translations: { en: '{count} properties found', es: '{count} propiedades encontradas' } },
  { key: 'results_no_results', category: 'results', translations: { en: 'No properties found', es: 'No se encontraron propiedades' } },
  { key: 'results_no_results_message', category: 'results', translations: { en: 'Try adjusting your search criteria', es: 'Intente ajustar sus criterios de búsqueda' } },
  { key: 'sort_label', category: 'results', translations: { en: 'Sort by', es: 'Ordenar por' } },
  { key: 'sort_newest', category: 'results', translations: { en: 'Newest Listings', es: 'Más Recientes' } },
  { key: 'sort_oldest', category: 'results', translations: { en: 'Oldest Listings', es: 'Más Antiguos' } },
  { key: 'sort_recently_updated', category: 'results', translations: { en: 'Recently Updated', es: 'Actualizados Recientemente' } },
  { key: 'sort_oldest_updated', category: 'results', translations: { en: 'Oldest Updated', es: 'Actualizados Hace Tiempo' } },
  { key: 'sort_price_asc', category: 'results', translations: { en: 'Price: Low to High', es: 'Precio: Menor a Mayor' } },
  { key: 'sort_price_desc', category: 'results', translations: { en: 'Price: High to Low', es: 'Precio: Mayor a Menor' } },
  { key: 'sort_featured', category: 'results', translations: { en: 'Featured First', es: 'Destacados Primero' } },
  { key: 'sort_location', category: 'results', translations: { en: 'By Location', es: 'Por Ubicación' } },
  { key: 'view_toggle', category: 'results', translations: { en: 'View toggle', es: 'Cambiar vista' } },
  { key: 'view_grid', category: 'results', translations: { en: 'Grid view', es: 'Vista cuadrícula' } },
  { key: 'view_list', category: 'results', translations: { en: 'List view', es: 'Vista lista' } },
  { key: 'view_map', category: 'results', translations: { en: 'Map view', es: 'Vista mapa' } },
  { key: 'back_to_results', category: 'results', translations: { en: 'Back to Results', es: 'Volver a Resultados' } },
  { key: 'sort_date_desc', category: 'results', translations: { en: 'Recently Added', es: 'Añadidos Recientemente' } },

  // ── Property Card ────────────────────────────────────────
  { key: 'card_bedrooms', category: 'card', translations: { en: 'beds', es: 'hab.' } },
  { key: 'card_bathrooms', category: 'card', translations: { en: 'baths', es: 'baños' } },
  { key: 'card_build_size', category: 'card', translations: { en: 'Built', es: 'Construido' } },
  { key: 'card_plot_size', category: 'card', translations: { en: 'plot', es: 'parcela' } },
  { key: 'card_terrace_size', category: 'card', translations: { en: 'terrace', es: 'terraza' } },
  { key: 'card_own', category: 'card', translations: { en: 'Own', es: 'Propio' } },
  { key: 'card_view_details', category: 'card', translations: { en: 'View Details', es: 'Ver Detalles' } },
  { key: 'card_featured', category: 'card', translations: { en: 'Featured', es: 'Destacado' } },
  { key: 'card_key_ready', category: 'card', translations: { en: 'Key Ready', es: 'Llave en mano' } },
  { key: 'card_for_sale', category: 'card', translations: { en: 'For Sale', es: 'En Venta' } },
  { key: 'card_for_rent', category: 'card', translations: { en: 'For Rent', es: 'En Alquiler' } },
  { key: 'card_holiday_rent', category: 'card', translations: { en: 'Holiday Rental', es: 'Alquiler Vacacional' } },
  { key: 'card_development', category: 'card', translations: { en: 'New Development', es: 'Obra Nueva' } },
  { key: 'card_offplan', category: 'card', translations: { en: 'Off Plan', es: 'Sobre Plano' } },
  { key: 'card_price_on_request', category: 'card', translations: { en: 'Price on Request', es: 'Precio bajo consulta' } },
  // Rental price period: "€1,750 – €2,450 / week"
  { key: 'price_per_night', category: 'card', translations: { en: 'night', es: 'noche' } },
  { key: 'price_per_week', category: 'card', translations: { en: 'week', es: 'semana' } },
  { key: 'price_per_month', category: 'card', translations: { en: 'month', es: 'mes' } },
  { key: 'card_built_area', category: 'card', translations: { en: 'Built Area', es: 'Superficie' } },
  { key: 'card_read_more', category: 'card', translations: { en: 'READ MORE', es: 'LEER MÁS' } },
  { key: 'card_toggle_favorite', category: 'card', translations: { en: 'Toggle favorite', es: 'Añadir o quitar de favoritos' } },
  // Badge on the "location first" card design (capitals by design)
  { key: 'card_badge_sale', category: 'card', translations: { en: 'RESALE', es: 'REVENTA' } },
  { key: 'card_badge_rent', category: 'card', translations: { en: 'FOR RENT', es: 'EN ALQUILER' } },
  { key: 'card_badge_holiday_rent', category: 'card', translations: { en: 'HOLIDAY RENT', es: 'ALQUILER VACACIONAL' } },
  { key: 'card_badge_development', category: 'card', translations: { en: 'NEW DEVELOPMENT', es: 'OBRA NUEVA' } },
  { key: 'card_badge_offplan', category: 'card', translations: { en: 'OFF PLAN', es: 'SOBRE PLANO' } },

  // ── Property Detail ──────────────────────────────────────
  { key: 'detail_description', category: 'detail', translations: { en: 'Description', es: 'Descripción' } },
  { key: 'detail_features', category: 'detail', translations: { en: 'Features', es: 'Características' } },
  { key: 'detail_specifications', category: 'detail', translations: { en: 'Specifications', es: 'Especificaciones' } },
  { key: 'detail_location', category: 'detail', translations: { en: 'Location', es: 'Ubicación' } },
  { key: 'detail_similar', category: 'detail', translations: { en: 'Similar Properties', es: 'Propiedades Similares' } },
  { key: 'detail_back', category: 'detail', translations: { en: 'Back to Results', es: 'Volver a Resultados' } },
  { key: 'detail_share', category: 'detail', translations: { en: 'Share', es: 'Compartir' } },
  { key: 'detail_save', category: 'detail', translations: { en: 'Save', es: 'Guardar' } },
  { key: 'detail_saved', category: 'detail', translations: { en: 'Saved', es: 'Guardado' } },
  { key: 'detail_video', category: 'detail', translations: { en: 'Video', es: 'Video' } },
  { key: 'detail_virtual_tour', category: 'detail', translations: { en: 'Virtual Tour', es: 'Tour Virtual' } },
  { key: 'detail_pdf', category: 'detail', translations: { en: 'PDF', es: 'PDF' } },
  { key: 'detail_energy_rating', category: 'detail', translations: { en: 'Energy Rating', es: 'Certificado Energético' } },
  { key: 'detail_development', category: 'detail', translations: { en: 'Development', es: 'Promoción' } },
  { key: 'detail_price_list', category: 'detail', translations: { en: 'Price list', es: 'Lista de precios' } },
  { key: 'detail_unit', category: 'detail', translations: { en: 'Unit', es: 'Unidad' } },
  { key: 'detail_unit_type', category: 'detail', translations: { en: 'Type', es: 'Tipo' } },
  { key: 'detail_unit_status', category: 'detail', translations: { en: 'Status', es: 'Estado' } },
  { key: 'detail_unit_available', category: 'detail', translations: { en: 'Available', es: 'Disponible' } },
  { key: 'detail_unit_reserved', category: 'detail', translations: { en: 'Reserved', es: 'Reservado' } },
  { key: 'detail_unit_sold', category: 'detail', translations: { en: 'Sold', es: 'Vendido' } },
  { key: 'detail_units_available', category: 'detail', translations: { en: '{count} of {total} units available', es: '{count} de {total} unidades disponibles' } },
  { key: 'detail_community_fees', category: 'detail', translations: { en: 'Community Fees', es: 'Gastos de Comunidad' } },
  { key: 'detail_year_built', category: 'detail', translations: { en: 'Year Built', es: 'Año de Construcción' } },
  { key: 'detail_price', category: 'detail', translations: { en: 'Price', es: 'Precio' } },
  { key: 'detail_bedrooms', category: 'detail', translations: { en: 'Bedrooms', es: 'Dormitorios' } },
  { key: 'detail_bathrooms', category: 'detail', translations: { en: 'Bathrooms', es: 'Baños' } },
  { key: 'detail_built_area', category: 'detail', translations: { en: 'Built Area', es: 'Superficie Construida' } },
  { key: 'detail_plot_size', category: 'detail', translations: { en: 'Plot Size', es: 'Parcela' } },
  { key: 'detail_terrace', category: 'detail', translations: { en: 'Terrace', es: 'Terraza' } },
  { key: 'detail_floor', category: 'detail', translations: { en: 'Floor', es: 'Planta' } },
  { key: 'detail_garden', category: 'detail', translations: { en: 'Garden', es: 'Jardín' } },
  { key: 'detail_orientation', category: 'detail', translations: { en: 'Orientation', es: 'Orientación' } },
  { key: 'detail_parking', category: 'detail', translations: { en: 'Parking', es: 'Aparcamiento' } },
  { key: 'detail_per_month', category: 'detail', translations: { en: 'month', es: 'mes' } },
  { key: 'detail_status', category: 'detail', translations: { en: 'Status', es: 'Estado' } },
  { key: 'detail_type', category: 'detail', translations: { en: 'Type', es: 'Tipo' } },
  { key: 'detail_property_type', category: 'detail', translations: { en: 'Property Type', es: 'Tipo de Propiedad' } },
  { key: 'detail_listing_type', category: 'detail', translations: { en: 'Listing Type', es: 'Tipo de Operación' } },
  { key: 'detail_status_sold', category: 'detail', translations: { en: 'Sold', es: 'Vendido' } },
  { key: 'detail_status_rented', category: 'detail', translations: { en: 'Rented', es: 'Alquilado' } },
  { key: 'detail_ref', category: 'detail', translations: { en: 'Ref', es: 'Ref' } },
  { key: 'detail_address', category: 'detail', translations: { en: 'Address', es: 'Dirección' } },
  { key: 'detail_property_info', category: 'detail', translations: { en: 'Property Information', es: 'Información de la Propiedad' } },
  { key: 'detail_zip', category: 'detail', translations: { en: 'Zip Code', es: 'Código Postal' } },
  { key: 'detail_energy_na', category: 'detail', translations: { en: 'N/A', es: 'N/D' } },
  { key: 'detail_energy_not_available', category: 'detail', translations: { en: 'Energy rating not available', es: 'Certificado energético no disponible' } },
  { key: 'detail_energy_rating_value', category: 'detail', translations: { en: 'Energy rating {rating}', es: 'Certificado energético {rating}' } },
  { key: 'detail_features_general', category: 'detail', translations: { en: 'General', es: 'General' } },
  { key: 'detail_property_video', category: 'detail', translations: { en: 'Property video', es: 'Vídeo de la propiedad' } },
  // Listing-type badge on the property page
  { key: 'detail_status_sale', category: 'detail', translations: { en: 'For Sale', es: 'En Venta' } },
  { key: 'detail_status_rent', category: 'detail', translations: { en: 'For Rent', es: 'En Alquiler' } },
  { key: 'detail_status_holiday_rent', category: 'detail', translations: { en: 'Holiday Rent', es: 'Alquiler Vacacional' } },
  { key: 'detail_status_development', category: 'detail', translations: { en: 'Development', es: 'Promoción' } },
  { key: 'detail_status_offplan', category: 'detail', translations: { en: 'Off Plan', es: 'Sobre Plano' } },

  // ── Inquiry Form ─────────────────────────────────────────
  { key: 'inquiry_title', category: 'inquiry', translations: { en: 'Contact Agent', es: 'Contactar Agente' } },
  { key: 'inquiry_first_name', category: 'inquiry', translations: { en: 'First Name', es: 'Nombre' } },
  { key: 'inquiry_last_name', category: 'inquiry', translations: { en: 'Last Name', es: 'Apellido' } },
  { key: 'inquiry_email', category: 'inquiry', translations: { en: 'Your Email', es: 'Tu Email' } },
  { key: 'inquiry_phone', category: 'inquiry', translations: { en: 'Your Phone', es: 'Tu Teléfono' } },
  { key: 'inquiry_message', category: 'inquiry', translations: { en: 'Message', es: 'Mensaje' } },
  { key: 'inquiry_send', category: 'inquiry', translations: { en: 'Send Inquiry', es: 'Enviar Consulta' } },
  { key: 'inquiry_sending', category: 'inquiry', translations: { en: 'Sending...', es: 'Enviando...' } },
  { key: 'inquiry_success', category: 'inquiry', translations: { en: 'Your inquiry has been sent successfully.', es: 'Su consulta ha sido enviada correctamente.' } },
  { key: 'inquiry_error', category: 'inquiry', translations: { en: 'Failed to send inquiry. Please try again.', es: 'Error al enviar la consulta. Inténtelo de nuevo.' } },
  { key: 'inquiry_privacy_prefix', category: 'inquiry', translations: { en: 'I accept the', es: 'Acepto la' } },
  { key: 'inquiry_privacy_label', category: 'inquiry', translations: { en: 'privacy policy', es: 'política de privacidad' } },
  { key: 'inquiry_privacy_url', category: 'inquiry', translations: { en: '/privacy-policy', es: '/politica-de-privacidad' } },
  { key: 'inquiry_default_message', category: 'inquiry', translations: { en: 'I am interested in the property "{title}" (Ref: {ref}). Please contact me with more information.', es: 'Estoy interesado en la propiedad "{title}" (Ref: {ref}). Por favor, contácteme con más información.' } },
  { key: 'inquiry_for_sale', category: 'inquiry', translations: { en: 'for sale', es: 'en venta' } },
  { key: 'inquiry_for_rent', category: 'inquiry', translations: { en: 'for rent', es: 'en alquiler' } },
  { key: 'inquiry_for_holiday_rent', category: 'inquiry', translations: { en: 'for holiday rent', es: 'en alquiler vacacional' } },
  { key: 'inquiry_in_location', category: 'inquiry', translations: { en: 'in {location}', es: 'en {location}' } },

  // ── Wishlist ─────────────────────────────────────────────
  { key: 'wishlist_title', category: 'wishlist', translations: { en: 'Wishlist', es: 'Lista de Deseos' } },
  { key: 'wishlist_empty', category: 'wishlist', translations: { en: 'Your wishlist is empty', es: 'Tu lista de deseos está vacía' } },
  { key: 'wishlist_remove', category: 'wishlist', translations: { en: 'Remove', es: 'Eliminar' } },
  { key: 'wishlist_share', category: 'wishlist', translations: { en: 'Share Wishlist', es: 'Compartir Lista' } },
  { key: 'wishlist_compare', category: 'wishlist', translations: { en: 'Compare', es: 'Comparar' } },
  { key: 'wishlist_shared_banner', category: 'wishlist', translations: { en: 'Shared wishlist', es: 'Lista compartida' } },
  { key: 'wishlist_clear_confirm', category: 'wishlist', translations: { en: 'Remove all properties from your wishlist?', es: '¿Eliminar todas las propiedades de tu lista?' } },
  { key: 'wishlist_empty_hint', category: 'wishlist', translations: { en: 'Browse properties and tap the heart icon to save your favorites', es: 'Navega por las propiedades y pulsa el icono de corazón para guardar tus favoritos' } },
  { key: 'wishlist_sort', category: 'wishlist', translations: { en: 'Sort', es: 'Ordenar' } },
  { key: 'wishlist_share_text', category: 'wishlist', translations: { en: 'Check out my saved properties', es: 'Mira mis propiedades guardadas' } },
  { key: 'compare', category: 'wishlist', translations: { en: 'Compare', es: 'Comparar' } },
  { key: 'compare_properties', category: 'wishlist', translations: { en: 'Compare Properties', es: 'Comparar Propiedades' } },
  { key: 'compare_select_min', category: 'wishlist', translations: { en: 'Please select at least 2 properties to compare.', es: 'Seleccione al menos 2 propiedades para comparar.' } },
  { key: 'share_wishlist', category: 'wishlist', translations: { en: 'Share Your Wishlist', es: 'Compartir Tu Lista' } },
  { key: 'share_wishlist_desc', category: 'wishlist', translations: { en: 'Share this link with anyone to show them your saved properties:', es: 'Comparte este enlace para mostrar tus propiedades guardadas:' } },
  { key: 'email_wishlist', category: 'wishlist', translations: { en: 'Email Your Wishlist', es: 'Enviar Tu Lista por Email' } },
  { key: 'add_note', category: 'wishlist', translations: { en: 'Add Note', es: 'Añadir Nota' } },
  { key: 'add_personal_note', category: 'wishlist', translations: { en: 'Add a personal note...', es: 'Agregar una nota personal...' } },
  { key: 'note_placeholder', category: 'wishlist', translations: { en: 'Write your note here...', es: 'Escribe tu nota aquí...' } },
  { key: 'personal_message', category: 'wishlist', translations: { en: 'Personal Message', es: 'Mensaje Personal' } },
  { key: 'your_email_optional', category: 'wishlist', translations: { en: 'Your email (optional)', es: 'Tu email (opcional)' } },
  { key: 'your_name_optional', category: 'wishlist', translations: { en: 'Your name (optional)', es: 'Tu nombre (opcional)' } },
  // Wishlist PDF download
  { key: 'wishlist_pdf_title', category: 'wishlist', translations: { en: 'Property Wishlist', es: 'Lista de Propiedades Favoritas' } },
  { key: 'wishlist_pdf_count_one', category: 'wishlist', translations: { en: '{n} Property Saved', es: '{n} Propiedad Guardada' } },
  { key: 'wishlist_pdf_count', category: 'wishlist', translations: { en: '{n} Properties Saved', es: '{n} Propiedades Guardadas' } },
  { key: 'wishlist_pdf_property_of', category: 'wishlist', translations: { en: 'Property {index} of {total}', es: 'Propiedad {index} de {total}' } },
  { key: 'wishlist_pdf_page_of', category: 'wishlist', translations: { en: 'Page {index} of {total}', es: 'Página {index} de {total}' } },
  { key: 'wishlist_pdf_collection', category: 'wishlist', translations: { en: 'Property Collection', es: 'Colección de Propiedades' } },

  // ── Map ──────────────────────────────────────────────────
  { key: 'map_search_address', category: 'map', translations: { en: 'Search address...', es: 'Buscar dirección...' } },
  { key: 'map_radius', category: 'map', translations: { en: 'Radius', es: 'Radio' } },
  { key: 'map_view_all', category: 'map', translations: { en: 'View All', es: 'Ver Todo' } },
  { key: 'map_zones', category: 'map', translations: { en: 'Zones', es: 'Zonas' } },
  { key: 'map_properties', category: 'map', translations: { en: 'Properties', es: 'Propiedades' } },
  { key: 'map_list_view', category: 'map', translations: { en: 'List View', es: 'Vista de Lista' } },
  { key: 'map_map_view', category: 'map', translations: { en: 'Map View', es: 'Vista de Mapa' } },
  { key: 'map_unavailable', category: 'map', translations: { en: 'Map could not be loaded', es: 'No se pudo cargar el mapa' } },
  { key: 'zones', category: 'map', translations: { en: 'areas', es: 'zonas' } },
  { key: 'map_areas', category: 'map', translations: { en: 'Areas', es: 'Zonas' } },
  { key: 'map_show', category: 'map', translations: { en: 'Show', es: 'Mostrar' } },
  { key: 'map_within', category: 'map', translations: { en: 'Within', es: 'En un radio de' } },
  { key: 'map_address_not_found', category: 'map', translations: { en: 'We could not find that place', es: 'No hemos encontrado ese lugar' } },
  { key: 'map_approximate_location', category: 'map', translations: { en: 'Approximate location', es: 'Ubicación aproximada' } },
  { key: 'map_price_on_request_short', category: 'map', translations: { en: 'P.O.R.', es: 'Consultar' } },
  { key: 'map_no_results', category: 'map', translations: { en: 'No properties to show on the map for this search', es: 'No hay propiedades que mostrar en el mapa para esta búsqueda' } },
  { key: 'map_load_error', category: 'map', translations: { en: 'Properties could not be loaded on the map', es: 'No se pudieron cargar las propiedades en el mapa' } },
  { key: 'map_search_this_area', category: 'map', translations: { en: 'Search this area', es: 'Buscar en esta zona' } },
  { key: 'map_showing_area', category: 'map', translations: { en: 'Showing this area', es: 'Mostrando esta zona' } },
  { key: 'map_truncated', category: 'map', translations: { en: 'Zoom in or filter to see every property', es: 'Acerque el mapa o filtre para ver todas las propiedades' } },

  // ── AI Chat ──────────────────────────────────────────────
  { key: 'chat_toggle', category: 'chat', translations: { en: 'Chat with AI', es: 'Chatear con IA' } },
  { key: 'chat_title', category: 'chat', translations: { en: 'Property Assistant', es: 'Asistente de Propiedades' } },
  { key: 'chat_welcome', category: 'chat', translations: { en: 'Ask me anything about our properties!', es: '¡Pregúntame lo que quieras sobre nuestras propiedades!' } },
  { key: 'chat_error', category: 'chat', translations: { en: 'Sorry, something went wrong. Please try again.', es: 'Lo sentimos, algo salió mal. Inténtelo de nuevo.' } },
  { key: 'chat_placeholder', category: 'chat', translations: { en: 'Type your question...', es: 'Escribe tu pregunta...' } },

  // ── Pagination ───────────────────────────────────────────
  { key: 'pagination_prev', category: 'pagination', translations: { en: 'Previous', es: 'Anterior' } },
  { key: 'pagination_next', category: 'pagination', translations: { en: 'Next', es: 'Siguiente' } },
  { key: 'pagination_page', category: 'pagination', translations: { en: 'Page', es: 'Página' } },
  { key: 'pagination_label', category: 'pagination', translations: { en: 'Pagination', es: 'Paginación' } },

  // ── Mortgage Calculator ──────────────────────────────────
  { key: 'mortgage_title', category: 'mortgage', translations: { en: 'Mortgage Calculator', es: 'Calculadora de Hipoteca' } },
  { key: 'mortgage_price', category: 'mortgage', translations: { en: 'Property Price', es: 'Precio de la Propiedad' } },
  { key: 'mortgage_down_payment', category: 'mortgage', translations: { en: 'Down Payment', es: 'Entrada' } },
  { key: 'mortgage_interest', category: 'mortgage', translations: { en: 'Interest Rate', es: 'Tasa de Interés' } },
  { key: 'mortgage_years', category: 'mortgage', translations: { en: 'Years', es: 'Años' } },
  { key: 'mortgage_monthly', category: 'mortgage', translations: { en: 'Monthly Payment', es: 'Pago Mensual' } },

  // ── General ──────────────────────────────────────────────
  { key: 'yes', category: 'general', translations: { en: 'Yes', es: 'Sí' } },
  { key: 'loading', category: 'general', translations: { en: 'Loading...', es: 'Cargando...' } },
  { key: 'error', category: 'general', translations: { en: 'An error occurred', es: 'Ocurrió un error' } },
  { key: 'close', category: 'general', translations: { en: 'Close', es: 'Cerrar' } },
  { key: 'currency_label', category: 'general', translations: { en: 'Currency', es: 'Moneda' } },
  { key: 'language_label', category: 'general', translations: { en: 'Language', es: 'Idioma' } },
  { key: 'featured', category: 'general', translations: { en: 'Featured', es: 'Destacado' } },
  { key: 'cancel', category: 'general', translations: { en: 'Cancel', es: 'Cancelar' } },
  { key: 'clear', category: 'general', translations: { en: 'Clear', es: 'Limpiar' } },
  { key: 'copy', category: 'general', translations: { en: 'Copy', es: 'Copiar' } },
  { key: 'copied', category: 'general', translations: { en: 'Copied!', es: '¡Copiado!' } },
  { key: 'save', category: 'general', translations: { en: 'Save', es: 'Guardar' } },
  { key: 'edit', category: 'general', translations: { en: 'Edit', es: 'Editar' } },
  { key: 'share', category: 'general', translations: { en: 'Share', es: 'Compartir' } },
  { key: 'send_email', category: 'general', translations: { en: 'Send Email', es: 'Enviar Email' } },
  { key: 'send_to', category: 'general', translations: { en: 'Send to:', es: 'Enviar a:' } },
  { key: 'sending', category: 'general', translations: { en: 'Sending...', es: 'Enviando...' } },
  { key: 'email', category: 'general', translations: { en: 'Email', es: 'Email' } },
  { key: 'email_error', category: 'general', translations: { en: 'Failed to send. Please try again.', es: 'Error al enviar. Inténtelo de nuevo.' } },
  { key: 'email_sent', category: 'general', translations: { en: 'Email sent successfully!', es: '¡Email enviado correctamente!' } },
  { key: 'download_pdf', category: 'general', translations: { en: 'Download PDF', es: 'Descargar PDF' } },
  { key: 'qr_code', category: 'general', translations: { en: 'QR Code', es: 'Código QR' } },
  { key: 'read_less', category: 'general', translations: { en: 'Read Less', es: 'Leer Menos' } },
  { key: 'read_more', category: 'general', translations: { en: 'Read More', es: 'Leer Más' } },
  { key: 'view_all', category: 'general', translations: { en: 'View All Properties', es: 'Ver Todas las Propiedades' } },
  { key: 'view_details', category: 'general', translations: { en: 'View Details', es: 'Ver Detalles' } },
  { key: 'properties', category: 'general', translations: { en: 'properties', es: 'propiedades' } },
  { key: 'property_singular', category: 'general', translations: { en: 'property', es: 'propiedad' } },
  { key: 'type', category: 'general', translations: { en: 'Type', es: 'Tipo' } },
  { key: 'reference', category: 'general', translations: { en: 'Ref', es: 'Ref' } },
  { key: 'feature', category: 'general', translations: { en: 'Feature', es: 'Característica' } },
  { key: 'no_results', category: 'general', translations: { en: 'No results', es: 'Sin resultados' } },
  { key: 'beds', category: 'general', translations: { en: 'beds', es: 'hab.' } },
  { key: 'baths', category: 'general', translations: { en: 'baths', es: 'baños' } },
  { key: 'bedrooms', category: 'general', translations: { en: 'Bedrooms', es: 'Dormitorios' } },
  { key: 'bathrooms', category: 'general', translations: { en: 'Bathrooms', es: 'Baños' } },
  { key: 'location', category: 'general', translations: { en: 'Location', es: 'Ubicación' } },
  { key: 'price', category: 'general', translations: { en: 'Price', es: 'Precio' } },
  { key: 'wishlist', category: 'general', translations: { en: 'Wishlist', es: 'Lista de Deseos' } },
  { key: 'copy_link', category: 'general', translations: { en: 'Copy Link', es: 'Copiar Enlace' } },
];

export const KEY_TO_CATEGORY: Record<string, string> = {};
for (const label of DEFAULT_LABELS) {
  KEY_TO_CATEGORY[label.key] = label.category;
}

// Earlier default texts. A client's label still holding one of these was never
// edited by them, so it follows the new default; anything else they typed wins.
export const PREVIOUS_DEFAULTS: Record<string, Record<string, string[]>> = {
  location_dropdown2_label: { en: ['Sub-location'], es: ['Sub-ubicacion'] },
  property_type_all: { en: ['All Types'], es: ['Todos los Tipos'] },
  price_min: { en: ['Min Price'], es: ['Precio Minimo'] },
  price_max: { en: ['Max Price'], es: ['Precio Maximo'] },
  reference_placeholder: { en: ['Enter reference...'], es: ['Ingrese referencia...'] },
  // 10-05: Spanish defaults gained their accents (Banos -> Baños, Ano -> Año…).
  advanced_search: { es: ['Busqueda Avanzada'] },
  location_placeholder: { es: ['Ubicacion'] },
  location_search: { es: ['Buscar ubicacion...'] },
  location_dropdown1_label: { es: ['Ubicacion'] },
  location_dropdown3_label: { es: ['Area'] },
  location_select_parent: { es: ['Seleccione una ubicacion primero'] },
  bathrooms_label: { es: ['Banos'] },
  bathrooms_placeholder: { es: ['Banos'] },
  plot_size_label: { es: ['Tamano de Parcela (m2)'] },
  features_label: { es: ['Caracteristicas'] },
  more_filters: { es: ['Mas Filtros'] },
  features_search: { es: ['Buscar caracteristicas...'] },
  features_no_results: { es: ['No se encontraron caracteristicas'] },
  quick_features: { es: ['Caracteristicas Rapidas'] },
  results_no_results_message: { es: ['Intente ajustar sus criterios de busqueda'] },
  sort_newest: { es: ['Mas Recientes'] },
  sort_oldest: { es: ['Mas Antiguos'] },
  sort_location: { es: ['Por Ubicacion'] },
  view_grid: { es: ['Vista cuadricula'] },
  card_bathrooms: { es: ['banos'] },
  detail_description: { es: ['Descripcion'] },
  detail_features: { es: ['Caracteristicas'] },
  detail_location: { es: ['Ubicacion'] },
  detail_energy_rating: { es: ['Certificado Energetico'] },
  detail_year_built: { es: ['Ano de Construccion'] },
  detail_bathrooms: { es: ['Banos'] },
  detail_garden: { es: ['Jardin'] },
  detail_orientation: { es: ['Orientacion'] },
  detail_address: { es: ['Direccion'] },
  inquiry_phone: { es: ['Tu Telefono'] },
  inquiry_error: { es: ['Error al enviar la consulta. Intentelo de nuevo.'] },
  inquiry_privacy_label: { es: ['politica de privacidad'] },
  inquiry_default_message: { es: ['Estoy interesado en la propiedad "{title}" (Ref: {ref}). Por favor, contacteme con mas informacion.'] },
  wishlist_empty: { es: ['Tu lista de deseos esta vacia'] },
  wishlist_clear_confirm: { es: ['Eliminar todas las propiedades de tu lista?'] },
  wishlist_empty_hint: { es: ['Navega propiedades y pulsa el icono de corazon para guardar tus favoritos'] },
  add_note: { es: ['Anadir Nota'] },
  note_placeholder: { es: ['Escribe tu nota aqui...'] },
  map_search_address: { es: ['Buscar direccion...'] },
  chat_welcome: { es: ['Preguntame lo que quieras sobre nuestras propiedades!'] },
  chat_error: { es: ['Lo sentimos, algo salio mal. Intentelo de nuevo.'] },
  pagination_page: { es: ['Pagina'] },
  mortgage_interest: { es: ['Tasa de Interes'] },
  mortgage_years: { es: ['Anos'] },
  error: { es: ['Ocurrio un error'] },
  copied: { es: ['Copiado!'] },
  email_error: { es: ['Error al enviar. Intentelo de nuevo.'] },
  email_sent: { es: ['Email enviado correctamente!'] },
  qr_code: { es: ['Codigo QR'] },
  read_more: { es: ['Leer Mas'] },
  feature: { es: ['Caracteristica'] },
  baths: { es: ['banos'] },
  bathrooms: { es: ['Banos'] },
  location: { es: ['Ubicacion'] },
};
