"""Builds the property-type template seed from the Odoo property-type export.

    python scripts/build-property-type-template.py docs/property_types.csv

Input columns: lang, default_name (English), name (translated), rapi_code
(Resales type code, e.g. 1-4), default_parent_name.

Output: apps/api/src/modules/property-type-template/seed/property-type-template.seed.ts

- One node per English name; a name listed under several codes keeps all of
  them (Beach Bar = 4-22 and 4-23).
- Only English and Spanish translations are kept: those are Resales' own
  names. The export's other languages are machine translations that often
  get real-estate terms wrong (Plot -> de "Handlung", Commercial Plot -> de
  "Werbeklage", Land -> fr "Atterrir", Shop -> pt "Comprar"), and syncing them
  would overwrite clients' better translations. Add verified ones in Super Admin.
- ALIASES adds spellings feeds use that the export doesn't (Resales now sends
  "Finca - Cortijo" for code 2-6), plus plural group names older AI grouping
  created ("Apartments", "Villas").
"""
import collections
import csv
import json
import os
import sys

LANG = {'nb_NO': 'no', 'pt_BR': 'pt', 'ar_001': 'ar'}
KEEP_LANGS = {'en', 'es'}
ALIASES = {
    'Apartment': ['Apartments', 'Flats', 'Flat'],
    'House': ['Houses', 'Villas', 'Villas & Houses', 'Homes'],
    'Plot': ['Plots', 'Land & Plots', 'Plots & Land'],
    'Commercial': ['Commercial Properties', 'Commercial Property'],
    'Finca - Rural Estate': ['Finca - Cortijo', 'Finca', 'Cortijo', 'Country House'],
    'Detached Villa': ['Villa'],
    'Semi-Detached House': ['Semi Detached House', 'Semi-Detached Villa'],
    'Townhouse': ['Town House'],
}
OUT = os.path.join(os.path.dirname(__file__), '..', 'apps', 'api', 'src', 'modules',
                   'property-type-template', 'seed', 'property-type-template.seed.ts')


def lang_code(lang):
    return LANG.get(lang, lang.split('_')[0])


rows = []
for path in sys.argv[1:]:
    with open(path, encoding='utf-8') as f:
        rows.extend(csv.DictReader(f))

types = collections.OrderedDict()   # English name -> node
for r in rows:
    name = r['default_name'].strip()
    n = types.setdefault(name, {'name': name, 'parent': r['default_parent_name'].strip() or None,
                                'codes': [], 'tr': {}})
    code = r['rapi_code'].strip()
    if code and code not in n['codes']:
        n['codes'].append(code)
    translated = r['name'].strip()
    if translated and lang_code(r['lang']) in KEEP_LANGS:
        n['tr'][lang_code(r['lang'])] = translated
for n in types.values():
    n['tr']['en'] = n['name']
    n['codes'].sort(key=lambda c: [int(x) if x.isdigit() else x for x in c.split('-')])

groups = sorted([n for n in types.values() if not n['parent']], key=lambda n: n['codes'][0] if n['codes'] else n['name'])
children = sorted([n for n in types.values() if n['parent']],
                  key=lambda n: (n['parent'], [int(x) for x in n['codes'][0].split('-')] if n['codes'] else [999]))
order = groups + children
index = {n['name']: i for i, n in enumerate(order)}
missing_parents = {n['parent'] for n in children if n['parent'] not in index}
assert not missing_parents, missing_parents

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
    f.write('// Generated by scripts/build-property-type-template.py from docs/property_types.csv\n')
    f.write('// (Odoo export with Resales type codes). Regenerate rather than edit by hand; after\n')
    f.write('// the first migration the template lives in the database and is edited from\n')
    f.write('// Super Admin -> Property Type Template.\n//\n')
    f.write('// Row: [parentIndex (-1 = group), English name, Resales codes, translations, aliases]\n')
    f.write('export type PropertyTypeSeedRow = [number, string, string[], Record<string, string>, string[]];\n\n')
    f.write('export const PROPERTY_TYPE_TEMPLATE_SEED: PropertyTypeSeedRow[] = [\n')
    for n in order:
        parent = index[n['parent']] if n['parent'] else -1
        tr = dict(sorted(n['tr'].items()))
        f.write('  ' + json.dumps([parent, n['name'], n['codes'], tr, ALIASES.get(n['name'], [])], ensure_ascii=False) + ',\n')
    f.write('];\n')

langs = collections.Counter(l for n in order for l in n['tr'])
print('groups:', len(groups), 'types:', len(children), 'languages:', dict(langs), '->', os.path.relpath(OUT))
